In [6]:
import pandas as pd
import numpy as np

1. Check the data

In [8]:
df.head()

,Attrition,Business Travel,CF_age band,CF_attrition label,Department,Education Field,emp no,Employee Number,Gender,Job Role,...,Performance Rating,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager
0,Yes,Travel_Rarely,35 - 44,Ex-Employees,Sales,Life Sciences,STAFF-1,1,Female,Sales Executive,...,3,1,80,0,8,1,6,4,0,5
1,No,Travel_Frequently,45 - 54,Current Employees,R&D,Life Sciences,STAFF-2,2,Male,Research Scientist,...,4,4,80,1,10,3,10,7,1,7
2,Yes,Travel_Rarely,35 - 44,Ex-Employees,R&D,Other,STAFF-4,4,Male,Laboratory Technician,...,3,2,80,0,7,3,0,0,0,0
3,No,Travel_Frequently,25 - 34,Current Employees,R&D,Life Sciences,STAFF-5,5,Female,Research Scientist,...,3,3,80,0,8,3,8,7,3,0
4,No,Travel_Rarely,25 - 34,Current Employees,R&D,Medical,STAFF-7,7,Male,Laboratory Technician,...,3,4,80,1,6,3,2,2,2,2

In [9]:
df.tail()

,Attrition,Business Travel,CF_age band,CF_attrition label,Department,Education Field,emp no,Employee Number,Gender,Job Role,...,Performance Rating,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager
1465,Yes,Non-Travel,25 - 34,Ex-Employees,R&D,Technical Degree,STAFF-1905,1905,Male,Research Scientist,...,4,2,80,1,5,3,5,2,3,0
1466,Yes,Travel_Frequently,25 - 34,Ex-Employees,R&D,Life Sciences,STAFF-1868,1868,Male,Research Scientist,...,4,2,80,0,1,2,1,0,1,0
1467,Yes,Travel_Frequently,35 - 44,Ex-Employees,Sales,Other,STAFF-1667,1667,Male,Sales Executive,...,4,1,80,0,13,4,11,9,6,7
1468,Yes,Travel_Rarely,Under 25,Ex-Employees,R&D,Life Sciences,STAFF-1878,1878,Male,Research Scientist,...,4,1,80,0,1,3,1,0,0,0
1469,Yes,Travel_Rarely,Under 25,Ex-Employees,Sales,Life Sciences,STAFF-1702,1702,Male,Sales Representative,...,4,2,80,1,3,3,3,2,0,2

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Attrition                   1470 non-null   object
 1   Business Travel             1470 non-null   object
 2   CF_age band                 1470 non-null   object
 3   CF_attrition label          1470 non-null   object
 4   Department                  1470 non-null   object
 5   Education Field             1470 non-null   object
 6   emp no                      1470 non-null   object
 7   Employee Number             1470 non-null   int64
 8   Gender                      1470 non-null   object
 9   Job Role                    1470 non-null   object
 10  Marital Status              1470 non-null   object
 11  Over Time                   1470 non-null   object
 12  Over18                      1470 non-null   object
 13  Training Times Last Year    1470 non-null   int64
 14  Age                         1470 non-null   int64
 15  CF_current Employee         1470 non-null   int64
 16  Daily Rate                  1470 non-null   int64
 17  Distance From Home          1470 non-null   int64
 18  Education                   1470 non-null   object
 19  Employee Count              1470 non-null   int64
 20  Environment Satisfaction    1470 non-null   int64
 21  Hourly Rate                 1470 non-null   int64
 22  Job Involvement             1470 non-null   int64
 23  Job Level                   1470 non-null   int64
 24  Job Satisfaction            1470 non-null   int64
 25  Monthly Income              1470 non-null   int64
 26  Monthly Rate                1470 non-null   int64
 27  Num Companies Worked        1470 non-null   int64
 28  Percent Salary Hike         1470 non-null   int64
 29  Performance Rating          1470 non-null   int64
 30  Relationship Satisfaction   1470 non-null   int64
 31  Standard Hours              1470 non-null   int64
 32  Stock Option Level          1470 non-null   int64
 33  Total Working Years         1470 non-null   int64
 34  Work Life Balance           1470 non-null   int64
 35  Years At Company            1470 non-null   int64
 36  Years In Current Role       1470 non-null   int64
 37  Years Since Last Promotion  1470 non-null   int64
 38  Years With Curr Manager     1470 non-null   int64
dtypes: int64(26), object(13)
memory usage: 448.0+ KB

In [11]:
df.describe()

,Employee Number,Training Times Last Year,Age,CF_current Employee,Daily Rate,Distance From Home,Employee Count,Environment Satisfaction,Hourly Rate,Job Involvement,...,Performance Rating,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,1024.865306,2.799320,36.923810,0.838776,802.485714,9.192517,1.0,2.721769,65.891156,2.729932,...,3.153741,2.712245,80.0,0.793878,11.279592,2.761224,7.008163,4.229252,2.187755,4.123129
std,602.024335,1.289271,9.135373,0.367863,403.509100,8.106864,0.0,1.093082,20.329428,0.711561,...,0.360824,1.081209,0.0,0.852077,7.780782,0.706476,6.126525,3.623137,3.222430,3.568136
min,1.000000,0.000000,18.000000,0.000000,102.000000,1.000000,1.0,1.000000,30.000000,1.000000,...,3.000000,1.000000,80.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,491.250000,2.000000,30.000000,1.000000,465.000000,2.000000,1.0,2.000000,48.000000,2.000000,...,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,1020.500000,3.000000,36.000000,1.000000,802.000000,7.000000,1.0,3.000000,66.000000,3.000000,...,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,1555.750000,3.000000,43.000000,1.000000,1157.000000,14.000000,1.0,4.000000,83.750000,3.000000,...,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,2068.000000,6.000000,60.000000,1.000000,1499.000000,29.000000,1.0,4.000000,100.000000,4.000000,...,4.000000,4.000000,80.0,3.000000,40.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [12]:
df.shape

(1470, 39)

In [13]:
df.size

57330

In [14]:
df.columns

Index(['Attrition', 'Business Travel', 'CF_age band', 'CF_attrition label',
       'Department', 'Education Field', 'emp no', 'Employee Number', 'Gender',
       'Job Role', 'Marital Status', 'Over Time', 'Over18',
       'Training Times Last Year', 'Age', 'CF_current Employee', 'Daily Rate',
       'Distance From Home', 'Education', 'Employee Count',
       'Environment Satisfaction', 'Hourly Rate', 'Job Involvement',
       'Job Level', 'Job Satisfaction', 'Monthly Income', 'Monthly Rate',
       'Num Companies Worked', 'Percent Salary Hike', 'Performance Rating',
       'Relationship Satisfaction', 'Standard Hours', 'Stock Option Level',
       'Total Working Years', 'Work Life Balance', 'Years At Company',
       'Years In Current Role', 'Years Since Last Promotion',
       'Years With Curr Manager'],
      dtype='object')

2. Find missing values

In [ ]:
df = pd.read_excel(r"/content/HR Data.xlsx")

print(df.head())
print(df.isnull().sum())
print(df.duplicated().sum())

  Attrition    Business Travel CF_age band CF_attrition label Department  \
0       Yes      Travel_Rarely     35 - 44       Ex-Employees      Sales
1        No  Travel_Frequently     45 - 54  Current Employees        R&D
2       Yes      Travel_Rarely     35 - 44       Ex-Employees        R&D
3        No  Travel_Frequently     25 - 34  Current Employees        R&D
4        No      Travel_Rarely     25 - 34  Current Employees        R&D

  Education Field   emp no  Employee Number  Gender               Job Role  \
0   Life Sciences  STAFF-1                1  Female        Sales Executive
1   Life Sciences  STAFF-2                2    Male     Research Scientist
2           Other  STAFF-4                4    Male  Laboratory Technician
3   Life Sciences  STAFF-5                5  Female     Research Scientist
4         Medical  STAFF-7                7    Male  Laboratory Technician

   ... Performance Rating Relationship Satisfaction Standard Hours  \
0  ...                  3                         1             80
1  ...                  4                         4             80
2  ...                  3                         2             80
3  ...                  3                         3             80
4  ...                  3                         4             80

   Stock Option Level  Total Working Years  Work Life Balance  \
0                   0                    8                  1
1                   1                   10                  3
2                   0                    7                  3
3                   0                    8                  3
4                   1                    6                  3

   Years At Company  Years In Current Role Years Since Last Promotion  \
0                 6                      4                          0
1                10                      7                          1
2                 0                      0                          0
3                 8                      7                          3
4                 2                      2                          2

   Years With Curr Manager
0                        5
1                        7
2                        0
3                        0
4                        2

[5 rows x 39 columns]
Attrition                     0
Business Travel               0
CF_age band                   0
CF_attrition label            0
Department                    0
Education Field               0
emp no                        0
Employee Number               0
Gender                        0
Job Role                      0
Marital Status                0
Over Time                     0
Over18                        0
Training Times Last Year      0
Age                           0
CF_current Employee           0
Daily Rate                    0
Distance From Home            0
Education                     0
Employee Count                0
Environment Satisfaction      0
Hourly Rate                   0
Job Involvement               0
Job Level                     0
Job Satisfaction              0
Monthly Income                0
Monthly Rate                  0
Num Companies Worked          0
Percent Salary Hike           0
Performance Rating            0
Relationship Satisfaction     0
Standard Hours                0
Stock Option Level            0
Total Working Years           0
Work Life Balance             0
Years At Company              0
Years In Current Role         0
Years Since Last Promotion    0
Years With Curr Manager       0
dtype: int64
0

3. Handle missing values

In [15]:
df.dropna()

,Attrition,Business Travel,CF_age band,CF_attrition label,Department,Education Field,emp no,Employee Number,Gender,Job Role,...,Performance Rating,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager
0,Yes,Travel_Rarely,35 - 44,Ex-Employees,Sales,Life Sciences,STAFF-1,1,Female,Sales Executive,...,3,1,80,0,8,1,6,4,0,5
1,No,Travel_Frequently,45 - 54,Current Employees,R&D,Life Sciences,STAFF-2,2,Male,Research Scientist,...,4,4,80,1,10,3,10,7,1,7
2,Yes,Travel_Rarely,35 - 44,Ex-Employees,R&D,Other,STAFF-4,4,Male,Laboratory Technician,...,3,2,80,0,7,3,0,0,0,0
3,No,Travel_Frequently,25 - 34,Current Employees,R&D,Life Sciences,STAFF-5,5,Female,Research Scientist,...,3,3,80,0,8,3,8,7,3,0
4,No,Travel_Rarely,25 - 34,Current Employees,R&D,Medical,STAFF-7,7,Male,Laboratory Technician,...,3,4,80,1,6,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,Yes,Non-Travel,25 - 34,Ex-Employees,R&D,Technical Degree,STAFF-1905,1905,Male,Research Scientist,...,4,2,80,1,5,3,5,2,3,0
1466,Yes,Travel_Frequently,25 - 34,Ex-Employees,R&D,Life Sciences,STAFF-1868,1868,Male,Research Scientist,...,4,2,80,0,1,2,1,0,1,0
1467,Yes,Travel_Frequently,35 - 44,Ex-Employees,Sales,Other,STAFF-1667,1667,Male,Sales Executive,...,4,1,80,0,13,4,11,9,6,7
1468,Yes,Travel_Rarely,Under 25,Ex-Employees,R&D,Life Sciences,STAFF-1878,1878,Male,Research Scientist,...,4,1,80,0,1,3,1,0,0,0
1469,Yes,Travel_Rarely,Under 25,Ex-Employees,Sales,Life Sciences,STAFF-1702,1702,Male,Sales Representative,...,4,2,80,1,3,3,3,2,0,2

In [16]:
df.fillna(0)

,Attrition,Business Travel,CF_age band,CF_attrition label,Department,Education Field,emp no,Employee Number,Gender,Job Role,...,Performance Rating,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager
0,Yes,Travel_Rarely,35 - 44,Ex-Employees,Sales,Life Sciences,STAFF-1,1,Female,Sales Executive,...,3,1,80,0,8,1,6,4,0,5
1,No,Travel_Frequently,45 - 54,Current Employees,R&D,Life Sciences,STAFF-2,2,Male,Research Scientist,...,4,4,80,1,10,3,10,7,1,7
2,Yes,Travel_Rarely,35 - 44,Ex-Employees,R&D,Other,STAFF-4,4,Male,Laboratory Technician,...,3,2,80,0,7,3,0,0,0,0
3,No,Travel_Frequently,25 - 34,Current Employees,R&D,Life Sciences,STAFF-5,5,Female,Research Scientist,...,3,3,80,0,8,3,8,7,3,0
4,No,Travel_Rarely,25 - 34,Current Employees,R&D,Medical,STAFF-7,7,Male,Laboratory Technician,...,3,4,80,1,6,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,Yes,Non-Travel,25 - 34,Ex-Employees,R&D,Technical Degree,STAFF-1905,1905,Male,Research Scientist,...,4,2,80,1,5,3,5,2,3,0
1466,Yes,Travel_Frequently,25 - 34,Ex-Employees,R&D,Life Sciences,STAFF-1868,1868,Male,Research Scientist,...,4,2,80,0,1,2,1,0,1,0
1467,Yes,Travel_Frequently,35 - 44,Ex-Employees,Sales,Other,STAFF-1667,1667,Male,Sales Executive,...,4,1,80,0,13,4,11,9,6,7
1468,Yes,Travel_Rarely,Under 25,Ex-Employees,R&D,Life Sciences,STAFF-1878,1878,Male,Research Scientist,...,4,1,80,0,1,3,1,0,0,0
1469,Yes,Travel_Rarely,Under 25,Ex-Employees,Sales,Life Sciences,STAFF-1702,1702,Male,Sales Representative,...,4,2,80,1,3,3,3,2,0,2

In [17]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

/tmp/ipykernel_1329/1809399462.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

In [18]:
df["Monthly Income"].fillna(df["Monthly Income"].median(), inplace=True)

/tmp/ipykernel_1329/4118859556.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Monthly Income"].fillna(df["Monthly Income"].median(), inplace=True)

4. Remove duplicates

In [21]:
df.duplicated()
df.duplicated().sum()
df.drop_duplicates(inplace=True)

5. Correct data types

In [25]:
df.dtypes

df["Age"] = df["Age"].astype(int)
df["Monthly Income"] = df["Monthly Income"].astype(float)

6. CRemove extra spaces

In [28]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

7. Convert text to consistent case

In [29]:
df["Gender"] = df["Gender"].str.strip().str.title()
df["Department"] = df["Department"].str.strip().str.title()
df["Job Role"] = df["Job Role"].str.strip().str.title()

In [30]:
print(df["Gender"].unique())
print(df["Department"].unique())

['Female' 'Male']
['Sales' 'R&D' 'Hr']

9. Replace inconsistent values

In [31]:
print(df["Attrition"].value_counts())
print(df["Over Time"].value_counts())
print(df["Business Travel"].value_counts())

Attrition
No     1233
Yes     237
Name: count, dtype: int64
Over Time
No     1054
Yes     416
Name: count, dtype: int64
Business Travel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

10. Check categorical columns

In [32]:
for col in text_columns:
    print("\n", col)
    print(df[col].unique())

 Attrition
['Yes' 'No']

 Business Travel
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']

 CF_age band
['35 - 44' '45 - 54' '25 - 34' 'Over 55' 'Under 25']

 CF_attrition label
['Ex-Employees' 'Current Employees']

 Department
['Sales' 'R&D' 'Hr']

 Education Field
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']

 emp no
['STAFF-1' 'STAFF-2' 'STAFF-4' ... 'STAFF-1667' 'STAFF-1878' 'STAFF-1702']

 Gender
['Female' 'Male']

 Job Role
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']

 Marital Status
['Single' 'Married' 'Divorced']

 Over Time
['Yes' 'No']

 Over18
['Y']

 Education
['Associates Degree' 'High School' "Master's Degree" "Bachelor's Degree"
 'Doctoral Degree']

11. Check numerical columns for invalid values

In [33]:
print(df["Age"].min())
print(df["Age"].max())

print(df["Monthly Income"].min())
print(df["Monthly Income"].max())

print(df["Distance From Home"].min())
print(df["Distance From Home"].max())

18
60
1009.0
19999.0
1
29

cleaned data into a new Excel file.

In [35]:
df.to_excel("HR_Data_Cleaned.xlsx", index=False)